-- Seed all 30 NBA teams with their divisions, conferences, and NBA API team IDs

-- Eastern Conference - Atlantic Division
INSERT INTO teams (nba_team_id, team_name, abbreviation, division, conference) VALUES
(1, 'Atlanta Hawks', 'ATL', 'SOUTHEAST', 'EASTERN'),
(2, 'Boston Celtics', 'BOS', 'ATLANTIC', 'EASTERN'),
(3, 'Brooklyn Nets', 'BKN', 'ATLANTIC', 'EASTERN'),
(4, 'Charlotte Hornets', 'CHA', 'SOUTHEAST', 'EASTERN'),
(5, 'Chicago Bulls', 'CHI', 'CENTRAL', 'EASTERN'),
(6, 'Cleveland Cavaliers', 'CLE', 'CENTRAL', 'EASTERN'),
(7, 'Dallas Mavericks', 'DAL', 'SOUTHWEST', 'WESTERN'),
(8, 'Denver Nuggets', 'DEN', 'NORTHWEST', 'WESTERN'),
(9, 'Detroit Pistons', 'DET', 'CENTRAL', 'EASTERN'),
(10, 'Golden State Warriors', 'GSW', 'PACIFIC', 'WESTERN'),
(11, 'Houston Rockets', 'HOU', 'SOUTHWEST', 'WESTERN'),
(12, 'Indiana Pacers', 'IND', 'CENTRAL', 'EASTERN'),
(13, 'LA Clippers', 'LAC', 'PACIFIC', 'WESTERN'),
(14, 'Los Angeles Lakers', 'LAL', 'PACIFIC', 'WESTERN'),
(15, 'Memphis Grizzlies', 'MEM', 'SOUTHWEST', 'WESTERN'),
(16, 'Miami Heat', 'MIA', 'SOUTHEAST', 'EASTERN'),
(17, 'Milwaukee Bucks', 'MIL', 'CENTRAL', 'EASTERN'),
(18, 'Minnesota Timberwolves', 'MIN', 'NORTHWEST', 'WESTERN'),
(19, 'New Orleans Pelicans', 'NOP', 'SOUTHWEST', 'WESTERN'),
(20, 'New York Knicks', 'NYK', 'ATLANTIC', 'EASTERN'),
(21, 'Oklahoma City Thunder', 'OKC', 'NORTHWEST', 'WESTERN'),
(22, 'Orlando Magic', 'ORL', 'SOUTHEAST', 'EASTERN'),
(23, 'Philadelphia 76ers', 'PHI', 'ATLANTIC', 'EASTERN'),
(24, 'Phoenix Suns', 'PHX', 'PACIFIC', 'WESTERN'),
(25, 'Portland Trail Blazers', 'POR', 'NORTHWEST', 'WESTERN'),
(26, 'Sacramento Kings', 'SAC', 'PACIFIC', 'WESTERN'),
(27, 'San Antonio Spurs', 'SAS', 'SOUTHWEST', 'WESTERN'),
(28, 'Toronto Raptors', 'TOR', 'ATLANTIC', 'EASTERN'),
(29, 'Utah Jazz', 'UTA', 'NORTHWEST', 'WESTERN'),
(30, 'Washington Wizards', 'WAS', 'SOUTHEAST', 'EASTERN');
